import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../..');
const credentials=Object.fromEntries(fs.readFileSync(path.join(root,'infra/.env'),'utf8').split('\n').filter(line=>line.includes('=')&&!line.startsWith('#')).map(line=>[line.slice(0,line.indexOf('=')),line.slice(line.indexOf('=')+1)]));
const smoke=JSON.parse(fs.readFileSync(path.join(root,'verification/live-replay-smoke.json'),'utf8'));

test('real login queue case evidence plan and second user',async({page,browser})=>{
  const errors:string[]=[]; page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`/risks?run=${smoke.simulation.run}`);
  await page.getByLabel('Пользователь',{exact:true}).fill('engineer');
  await page.getByLabel('Пароль',{exact:true}).fill(credentials.DEMO_ENGINEER_PASSWORD);
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Очередь рисков',exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:/ТП-177/})).toBeVisible();
  await page.screenshot({path:path.join(root,'verification/live-queue-1440.png'),fullPage:true,animations:'disabled'});
  await page.getByRole('link',{name:/ТП-177/}).click();
  await expect(page.getByRole('heading',{name:/ТП-177/})).toBeVisible();
  await expect(page.getByRole('img',{name:'График измеренной и ожидаемой температуры',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Открыть записи'}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.screenshot({path:path.join(root,'verification/live-evidence.png'),fullPage:true,animations:'disabled'});
  await page.keyboard.press('Escape');
  for(const [width,height] of [[1440,1000],[1920,1080],[1024,768],[390,844]]){
    await page.setViewportSize({width,height});
    await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
    if(width<1024) await expect.poll(()=>page.locator('.sidebar').evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
    await page.screenshot({path:path.join(root,`verification/live-case-${width}.png`),fullPage:true,animations:'disabled'});
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Создать проект проверки'}).click();
  const dialog=page.getByRole('dialog',{name:'Проект проверочных мероприятий'});
  await dialog.getByLabel('Основание проекта').fill('Учебная проверка из реального браузера');
  await dialog.getByRole('button',{name:'Создать проект',exact:true}).click();
  await expect(page.getByRole('heading',{name:/План проверки/})).toBeVisible();
  const planUrl=page.url();
  await page.getByRole('button',{name:'Передать на согласование',exact:true}).click();
  const decision=page.getByRole('dialog',{name:'Передать на согласование'});
  await decision.getByLabel('Основание',{exact:true}).fill('Рассмотрены наблюдения и ограничения');
  await decision.getByRole('button',{name:'Записать решение'}).click();
  await expect(decision).not.toBeVisible();
  const second=await browser.newContext({viewport:{width:1440,height:1000}});
  const approver=await second.newPage();
  await approver.goto(planUrl);
  await approver.getByLabel('Пользователь',{exact:true}).fill('approver');
  await approver.getByLabel('Пароль',{exact:true}).fill(credentials.DEMO_APPROVER_PASSWORD);
  await approver.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(approver.getByRole('button',{name:'Согласовать',exact:true})).toBeVisible();
  await approver.getByRole('button',{name:'Согласовать',exact:true}).click();
  const approveDialog=approver.getByRole('dialog',{name:'Согласовать'});
  await approveDialog.getByLabel('Основание',{exact:true}).fill('Согласован только синтетический проверочный план');
  await approveDialog.getByRole('button',{name:'Записать решение'}).click();
  await expect(approveDialog).not.toBeVisible();
  await expect(approver.getByText('Согласован',{exact:true}).first()).toBeVisible();
  await approver.screenshot({path:path.join(root,'verification/live-plan-approved-1440.png'),fullPage:true,animations:'disabled'});
  await approver.reload();
  await expect(approver.getByText('Согласован',{exact:true}).first()).toBeVisible();
  await second.close();
  expect(errors).toEqual([]);
});
