import fs from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
const output = await openapiTS(new URL('../contracts/openapi.json', import.meta.url));
const expected = '/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n' + astToString(output);
const actual = await fs.readFile(new URL('../apps/web/src/api/generated.ts', import.meta.url), 'utf8');
if (actual !== expected) throw new Error('Generated TS drift: run npm run contracts:generate');
console.log('Generated TS matches OpenAPI');
