import { api } from '../api/client';
import { Badge, Banner, Card, DataTable, Empty, ErrorState, Loading, PageHeading } from '../design-system/components';
import { assetTypeLabel, locationLabel, date, expectData, fetchRiskQueue, href, percent, useResource } from './shared';

export function AssetsPage({ run }: { run: string }) {
  const assets = useResource(`assets-${run}`, async () => expectData(await api.GET('/api/v1/assets', { params: { query: { scenarioRunId: run, limit: 100, offset: 0 } } })));
  return <div className="feature-stack"><PageHeading eyebrow="Реестр" title="Обзор активов" subtitle="Оборудование и места измерения в выбранном запуске." />
    {assets.loading && !assets.data && <Loading />}{assets.error && !assets.data && <ErrorState message={assets.error.message} retry={assets.refresh} />}{assets.stale && <Banner tone="high" title="Сохраненный реестр">Проверьте обновления после восстановления связи.</Banner>}
    {assets.data && <Card title={`${assets.data.data.total} активов`} subtitle={`Время данных: ${date(assets.data.dataTime)}`}><DataTable label="Реестр активов"><thead><tr><th>Актив</th><th>Тип</th><th>Площадка</th><th>Место измерения</th></tr></thead><tbody>{assets.data.data.items.map(asset => <tr key={asset.assetId}><td><a href={href(`/assets/${encodeURIComponent(asset.assetId)}`, run)}><strong>{asset.name}</strong></a></td><td>{assetTypeLabel[asset.assetType]}</td><td>{asset.siteId}</td><td>{locationLabel(asset.measurementLocation)}</td></tr>)}</tbody></DataTable>{assets.data.data.items.length === 0 && <Empty title="Активов нет">Проверьте выбранный набор данных.</Empty>}</Card>}
  </div>;
}

export function AssetPage({ id, run }: { id: string; run: string }) {
  const asset = useResource(`asset-${run}-${id}`, async () => expectData(await api.GET('/api/v1/assets/{id}', { params: { path: { id }, query: { scenarioRunId: run } } })));
  const sources = useResource(`sources-${run}`, async () => expectData(await api.GET('/api/v1/sources', { params: { query: { scenarioRunId: run, limit: 1000, offset: 0 } } })));
  const risks = useResource(`asset-risks-${run}`, () => fetchRiskQueue(run, { includeNormal: true, limit: 1000, offset: 0 }));
  if (asset.loading && !asset.data) return <Loading />;
  if (asset.error && !asset.data) return <ErrorState message={asset.error.message} retry={asset.refresh} />;
  if (!asset.data) return <Empty title="Актив не найден">Проверьте ссылку.</Empty>;
  const item = asset.data.data;
  const entry = risks.data?.data.items.find(value => value.asset.assetId === id);
  return <div className="feature-stack"><PageHeading eyebrow="Актив" title={item.name} subtitle={`${assetTypeLabel[item.assetType]} · ${item.siteId}`} actions={entry?.caseId ? <a className="button button-primary" href={href(`/diagnostics/cases/${encodeURIComponent(entry.caseId)}`, run)}>Открыть случай</a> : undefined} />
    {(asset.stale || sources.stale || risks.stale) && <Banner tone="high" title="Показаны сохраненные данные">Состояние источников и анализа могло измениться.</Banner>}
    <div className="feature-support-grid"><Card title="Паспортная запись"><dl className="feature-definition"><div><dt>Идентификатор</dt><dd className="feature-mono">{item.assetId}</dd></div><div><dt>Место измерения</dt><dd>{locationLabel(item.measurementLocation)}</dd></div><div><dt>Площадка</dt><dd>{item.siteId}</dd></div><div><dt>Условный вес последствий</dt><dd>{percent(item.demoConsequenceWeight)}</dd></div></dl></Card><Card title="Текущий анализ" subtitle={entry ? `Анализ ${entry.analysis.analysisRunId}` : 'Данные анализа не получены'}>{entry ? <><Badge tone={entry.analysis.risk.priority}>{entry.analysis.risk.priority === 'unknown' ? 'Оценка неизвестна' : `Индекс ${entry.analysis.risk.score}/10`}</Badge><p className="feature-muted">Время данных: {date(entry.analysis.asOf)}. {entry.analysis.risk.label}</p>{entry.caseId && <a href={href(`/diagnostics/cases/${encodeURIComponent(entry.caseId)}`, run)}>Перейти к случаю →</a>}</> : <p className="feature-muted">Откройте очередь рисков для текущих наблюдений. Анализ по этому активу пока не доступен.</p>}</Card></div>
    <Card title="Источники" subtitle="Канал, физическое место, единица и допустимая давность">{sources.loading && !sources.data && <Loading />}{sources.error && !sources.data && <ErrorState message={sources.error.message} retry={sources.refresh} />}{sources.data && <DataTable label="Источники актива"><thead><tr><th>Канал</th><th>Место</th><th>Показатель / единица</th><th>Частота / давность</th></tr></thead><tbody>{sources.data.data.items.filter(source => source.assetId === id).map(source => <tr key={source.sourceId}><td><strong>{source.channel}</strong><span className="secondary-line feature-mono">{source.sourceId}</span></td><td>{source.location}</td><td>{source.metric} / {source.unit}</td><td>{source.frequencySeconds === null ? 'Событийный' : `${source.frequencySeconds} с`} / {source.maxAgeSeconds} с</td></tr>)}</tbody></DataTable>}{sources.data && !sources.data.data.items.some(source => source.assetId === id) && <Empty title="Источники не указаны">Проверить качество данных пока нельзя.</Empty>}</Card>
  </div>;
}

export function ModelsPage({ run }: { run: string }) {
  const models = useResource(`models-${run}`, async () => expectData(await api.GET('/api/v1/models', { params: { query: { scenarioRunId: run } } })));
  const sources = useResource(`sources-${run}`, async () => expectData(await api.GET('/api/v1/sources', { params: { query: { scenarioRunId: run, limit: 1000, offset: 0 } } })));
  return <div className="feature-stack"><PageHeading eyebrow="Прослеживаемость" title="Модели и данные" subtitle="Версии и источники текущего демонстрационного набора." />
    {(models.stale || sources.stale) && <Banner tone="high" title="Сохраненные сведения">Связь с сервером не подтверждена.</Banner>}
    <div className="feature-support-grid"><Card title="Численные модели">{models.loading && !models.data && <Loading />}{models.error && !models.data && <ErrorState message={models.error.message} retry={models.refresh} />}{models.data?.data.items.map(item => <dl className="feature-definition" key={item.modelVersion}><div><dt>Версия модели</dt><dd className="feature-mono">{item.modelVersion}</dd></div><div><dt>Политика</dt><dd className="feature-mono">{item.policyVersion}</dd></div><div><dt>Поддержка</dt><dd>{item.supportedAssetTypes.map(type => assetTypeLabel[type]).join(', ')}</dd></div><div><dt>Прогноз</dt><dd>{item.forecastEnabled ? 'Условный' : 'Выключен'}</dd></div></dl>)}{models.data?.data.items.length === 0 && <Empty title="Модели не представлены">Проверьте серверный реестр.</Empty>}</Card><Card title="Границы применения"><p className="feature-muted">Модель выдает расчетный остаток, тренд и пилотный индекс. Вероятность отказа не рассчитывается. Гипотеза не подтверждает дефект, а план не отдает команды оборудованию.</p><p className="feature-muted">REFERENCE содержит только иллюстрацию слайда. SIMULATION строится по синтетическим наблюдениям и не подтверждает точность на реальном оборудовании.</p></Card></div>
    <Card title="Реестр источников">{sources.loading && !sources.data && <Loading />}{sources.error && !sources.data && <ErrorState message={sources.error.message} retry={sources.refresh} />}{sources.data && <DataTable label="Реестр источников"><thead><tr><th>Источник</th><th>Актив / место</th><th>Показатель</th><th>Давность</th></tr></thead><tbody>{sources.data.data.items.map(source => <tr key={source.sourceId}><td className="feature-mono">{source.sourceId}</td><td><a href={href(`/assets/${encodeURIComponent(source.assetId)}`, run)}>{source.assetId}</a><span className="secondary-line">{source.location}</span></td><td>{source.metric} · {source.unit}</td><td>{source.maxAgeSeconds} с</td></tr>)}</tbody></DataTable>}{sources.data?.data.items.length === 0 && <Empty title="Источников нет">Проверьте выбранный запуск.</Empty>}</Card>
  </div>;
}
